name: Feature Request
title: "Feature: TITLE"
description: Request a new feature or an enhancement.
assignees: ["StormFX"]
labels: ["Enhancement", "New"]
projects: ["SFX-WoW/6"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: Please make sure that you set the title by replacing the `TITLE` text in the title field with something appropriate.
  - type: dropdown
    id: game-flavor
    attributes:
      label: Game Flavor
      description: Which flavor(s) of the game are you using? Select all that apply.
      multiple: true
      options:
        - Retail
        - Classic Era
        - Classic Wrath
      default: 0
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: Game Version
      description: Which version(s) of the game are you using? List any that apply.
      placeholder: e.g. 10.1.5
    validations:
      required: true
  - type: input
    id: addon-version
    attributes:
      label: Add-On Version
      description: Which version of the add-on are you using?
      placeholder: e.g. 10.1.5
    validations:
      required: true
  - type: textarea
    id: issue-desc
    attributes:
      label: Describe the Improvement
      description: Provide a clear and concise description of the feature or enhancement.
      placeholder: Describe the improvement.
    validations:
      required: true
  - type: textarea
    id: issue-code
    attributes:
      label: Example Code
      description: Provide an example of any code related to the improvement.
      placeholder: -- Your code here
      render: lua
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide links to any screenshots that may help to demonstrate the improvement.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any additional information that may be relevant to this request.
