name: Wiki Update
title: "Wiki: TITLE"
description: Report an issue with the Wiki or other documentation.
assignees: ["StormFX"]
labels: ["Documentation", "New", "Update"]
projects: ["SFX-WoW/7"]
body:
  - type: markdown
    attributes:
      value: >
        :warning: Please make sure that you set the title by replacing the `TITLE` text in the title field with something appropriate.
  - type: textarea
    id: issue-desc
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Proposed Changes
      description: Provide a clear and concise description of the proposed changes.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any additional information that may be relevant to this update.
